### ISSUE TITLE
Missing dependency for python3-gnupg

### ISSUE THREAD

**Issue by jronnblom** [keylime/keylime-deb#2]
Running on Ubuntu 18.04.

I needed to manually add python3-gnupg

apt-get install python3-gnupg

Maybe it should be added to the debian/control

```
Apr  9 14:16:55 u18dev4 systemd[1]: Started The Keylime registrar service.
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]: Using config file /etc/keylime.conf
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]: Traceback (most recent call last):
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:   File "/usr/bin/keylime_registrar", line 11, in <module>
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:     load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_registrar')()
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:     return get_distribution(dist).load_entry_point(group, name)
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:     return ep.load()
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:     return self.resolve()
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:     module = __import__(self.module_name, fromlist=['__name__'], level=0)
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:   File "/usr/lib/python3/dist-packages/keylime/cmd/registrar.py", line 8, in <module>
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:     from keylime import registrar_common
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:   File "/usr/lib/python3/dist-packages/keylime/registrar_common.py", line 23, in <module>
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:     from keylime import cloud_verifier_common
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:   File "/usr/lib/python3/dist-packages/keylime/cloud_verifier_common.py", line 21, in <module>
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:     from keylime.tpm.tpm_main import tpm
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:   File "/usr/lib/python3/dist-packages/keylime/tpm/tpm_main.py", line 26, in <module>
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:     from keylime.tpm import tpm_abstract
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:   File "/usr/lib/python3/dist-packages/keylime/tpm/tpm_abstract.py", line 24, in <module>
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:     from keylime import ima
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:   File "/usr/lib/python3/dist-packages/keylime/ima.py", line 14, in <module>
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]:     import gnupg
Apr  9 14:16:56 u18dev4 keylime_registrar[17799]: ModuleNotFoundError: No module named 'gnupg'

```

**Comment by galmasi** [comment]
I think Marcio's commit takes care of this.

**Comment by galmasi** [comment]
Agreed we can close this issue?

**Comment by jronnblom** [comment]
@galmasi yes we can close this.
